frontend/controllers/ActionController.php
<?php

namespace frontend\controllers;

use Yii;
use frontend\models\Action;
use frontend\models\ActionSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
/**
 * ActionController implements the CRUD actions for Action model.
 */
class ActionController extends Controller
{
    /**
     * @inheritdoc
     */

    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['login', 'error'],
                        'allow' => true,
                    ],
                    [
                        'actions' => ['logout', 'index','create','update','copy','delete','view'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

   /* public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }*/

    /**
     * Lists all Action models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new ActionSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Action model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    public function actionCopy($id)
    {
        //[_csrf-frontend] => 0oyzVUN00KfWvvKuwnfxNCbeKwC-jEIFfFihuiH_x06Kyv14JRmE9J37k5yAQ4MDabkda_HcLm84avH4FbCkIA==
        // [Action]
        $model = $this->findModel($id)->toArray();
        unset($model['id']);
        //echo '<pre>';
        //print_r($model);
        $copy = new Action();
        if ($copy->load(['Action'=>$model]) && $copy->save()) {
            return $this->redirect(['/']);
        }
        else{
            //echo '<pre>';
            print_r($copy->getErrors());
            //return $this->redirect(['/']);}
        }
    }

    /**
     * Creates a new Action model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Action();
        $share = $model->getShare();


        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            //$model->updateCounters(['id'=>1]);
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }




    /**
     * Updates an existing Action model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);
        $share = $model->getShare();
        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
                //'share' => $share
            ]);
        }
    }

    /**
     * Deletes an existing Action model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Action model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Action the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Action::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

frontend/views/action/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use kartik\time\TimePicker;
use kartik\datetime\DateTimePicker;
use yii\bootstrap;
use yii\widgets\Pjax;
use frontend\models\Shops;
use frontend\models\Fuel;
use richardfan\widget\JSRegister;

?>
<?/**
**@var $model frontend\models\Action
**/?>
<? Pjax::begin([]); ?>
<?$share = $model->getShare()?>

            <?php $form = ActiveForm::begin(); ?>
            <div class="row">
                <div class="col-xs-12 col-md-6">
                    <?= $form->field($model, 'date_start')->widget(DateTimePicker::className(), [
                        'name' => 'datetime_10',
                        'options' => ['placeholder' => 'Дата начала акции'],
                        'convertFormat' => false,
                        'pluginOptions' => [
                            'format' => 'yyyy-mm-dd HH:ii:ss',
                            'startDate' => date('yyyy-mm-dd H:i:s'),//''01-Mar-2014 12:00 AM'),
                            'todayHighlight' => true,
                            'clearButton' => false,
                        ]
                    ]); ?>
                </div>
                <div class="col-xs-12 col-md-6">
                    <?= $form->field($model, 'date_end')->widget(DateTimePicker::className(), [
                        'name' => 'datetime_10',
                        'options' => [
                            'placeholder' => 'Дата окончания акции'
                        ],
                        'convertFormat' => false,
                        'pluginOptions' => [
                            'format' => 'yyyy-mm-dd HH:ii:ss',
                            'startDate' => date('d-M-Y H:i:s'),
                            'todayHighlight' => true
                        ]
                    ]); ?>
                </div>
                <div class="col-xs-12 col-md-12">
                    <?= $form->field($model, 'description')
                        ->textarea(['maxlength' => true])
                        ->label('Описание акции') ?>
                </div>
                <div class="col-xs-12 col-md-6">
                    <?= $form->field($model, 'type')
                        ->textInput(['min' => 1,
                            'max' => 100,
                            'step' => 1,
                            'type' => 'number',
                            'value' => 1,
                            'placeholder' => ''])
                        ->label('Тип')
                    ?>
                </div>
                <div class="col-xs-12 col-md-6">
                    <?= $form->field($model, 'pos_article')
                        ->dropDownList(Fuel::getList())
                        ->label('Тип топлива')
                    ?>
                </div>

                <div class="col-xs-12 col-md-12">
                    <?= $form->field($model, 'shop_id')
                        ->dropDownList(Shops::getList())
                        ->label('АЗС на которой действует акция')
                    ?>
                </div>
            </div>
            <hr>
            <div class="row">
                <div class="col-xs-12 col-md-12 ">
                    <div class="row">
                        <div class="col-xs-12 col-md-6">
                            <div class="form-group field-action-type required">
                                <?= Html::label('Акция начинает действовать если залито литров', 'action-obem',
                                    ['class' => 'control-label', 'for' => 'action-obem']) ?>
                                <?= Html::textInput('Action[share_properties][0]', $share[0] ? $share[0]:1, [
                                    'min' => 0,
                                    'max' => 100,
                                    'step' => 1,
                                    'type' => 'number',
                                    'value' => 1,
                                    'placeholder' => '',
                                    'label' => 'test',
                                    'class' => 'form-control',
                                    'id' => 'action-obem'
                                ]) ?>
                                <div class="help-block"></div>
                            </div>
                        </div>
                        <div class="col-xs-12 col-md-6">
                            <div class="form-group field-action-type required">
                                <?= Html::label('Величина скидки', 'action-saleval') ?>
                                <?= Html::textInput('Action[share_properties][1]', $share[1] ? $share[1]:0, [
                                    'min' => 0,
                                    'max' => 100,
                                    'step' => 0.1,
                                    'type' => 'number',
                                    'placeholder' => 'Величина скидки от 0 до 100 (шаг 0.1)',
                                    'class' => 'form-control',
                                    'id' => 'action-saleval'
                                ])
                                ?>
                                <div class="help-block"></div>
                            </div>
                        </div>
                        <div class="col-xs-12 col-md-6">
                            <div class="form-group field-action-type required">
                                <?= Html::label('Скидка рассчитывается в виде', 'action-saleview') ?>
                                <?= Html::dropdownList('Action[share_properties][2]', $share[2] ? $share[2]:0,
                                    \frontend\models\SaleType::getList(),
                                    ['class' => 'form-control',
                                        'id' => 'action-saleview'
                                    ])
                                ?>
                            </div>
                        </div>
                        <div class="col-xs-12 col-md-6">
                            <div class="form-group field-action-type required">
                                <?= Html::label('Дни недели действия акции', 'action-saledays') ?>
                                <?= Html:: checkboxList('Action[share_properties][3]', $share[3] ? $share[3]:'',
                                    \frontend\models\ActionDays::getList(),
                                    ['class' => ["check_all"], 'separator' => '&nbsp;'])
                                // ->hint('Не выбран день')
                                // ->label('Дни недели действия акции')  ?>
                            </div>
                        </div>
                        <?php JSRegister::begin(); ?>
                        $('form .check_all ').on('change', 'input', function()
                        {
                            var prop = $(this).prop('checked');
                            var val = $(this).val();
                            if (val == 0)
                            {
                                $('form .check_all input').prop('checked',false);
                                $(this).prop('checked',prop);
                            }
                            else if (prop)
                            {
                                $('form .check_all input[value=0]').prop('checked',false);
                            }
                            if ( $('form .check_all input:checked').length == 7 && $('form .check_all input[value=0]').prop('checked')==false)
                            {
                                $('form .check_all input').prop('checked',false);
                                $('form .check_all input[value=0]').prop('checked',true);
                            }
                        });
                        <?php JSRegister::end(); ?>
                    </div>
                    <div class="row">
                        <div class="col-xs-12 col-md-6">
                            <div class="form-group field-action-type required">
                                <?= Html::label('Время действия акции  c', 'action-salefrom') ?>
                                <?= TimePicker::widget([
                                    'name' => 'Action[share_properties][4][0]',
                                    'value' => $share[4][0] ? $share[4][0] : '00:00',
                                    'pluginOptions' => [

                                        'showMeridian' => false,
                                        'showSeconds' => false,
                                        'minuteStep' => 1
                                    ]
                                ]); ?>
                            </div>
                        </div>
                        <div class="col-xs-12 col-md-6">
                            <div class="form-group field-action-type required">
                                <?= Html::label('до  ', 'action-saletill') ?>
                            <?= TimePicker::widget([
                                    'name' => 'Action[share_properties][4][1]',
                                'value' => $share[4][1] ? $share[4][1] : '00:00',
                                'pluginOptions' => [

                                    'showMeridian' => false,
                                    'showSeconds' => false,
                                    'minuteStep' => 1
                                ]
                            ]);?>
                            </div>
                        </div>
                        <?= Html::textInput('Action[share_properties][5]', $share[5]?$share[5]:0,[
                                'hidden'=>true
                        ])
                        ?>
                        <div class="col-xs-12 col-md-12">
                            <div class="form-group">
                                <?= Html::submitButton($model->isNewRecord
                                    ? Yii::t('app', 'Создать')
                                    : Yii::t('app', 'Обновить'),
                                    ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
                            </div>
                        </div>
                    </div>
                    <?php ActiveForm::end(); ?>
                </div>
            </div>
        </div>

<? Pjax::end([]); ?>

frontend/views/action/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\ActionSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="action-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'date_start') ?>

    <?= $form->field($model, 'date_end') ?>

    <?= $form->field($model, 'description') ?>

    <?= $form->field($model, 'type') ?>

    <?php // echo $form->field($model, 'pos_article') ?>

    <?php // echo $form->field($model, 'share_properties') ?>

    <?php // echo $form->field($model, 'shop_id') ?>

    <div class="form-group">
        <?= Html::submitButton(Yii::t('app', 'Search'), ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton(Yii::t('app', 'Reset'), ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

frontend/views/action/create.php
<?php

use yii\helpers\Html;
use yii\widgets\Pjax;

/* @var $this yii\web\View */
/* @var $model app\models\Action */

$this->title = Yii::t('app', 'Создать Акцию');
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Акции'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="action-create">

    <h1><?= Html::encode($this->title) ?></h1>
    <? Pjax::begin();?>
    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>
    <?Pjax::end();?>
</div>

frontend/views/action/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\widgets\Pjax;

/* @var $this yii\web\View */
/* @var $searchModel app\models\ActionSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = Yii::t('app', 'Акции');
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="action-index">

    <h1><?= Html::encode($this->title) ?></h1>
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <p>
        <?= Html::a(Yii::t('app', 'Создать Акцию'), ['create'], ['class' => 'btn btn-success']) ?>
    </p>
    <?php Pjax::begin(); ?>
    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'layout' => "{pager}\n{summary}\n{items}\n{pager}",
        'filterModel' => $searchModel,
        'pager'=> [
            'firstPageLabel'=>'⇚',
            'prevPageLabel'=>'⇦',
            'nextPageLabel'=>'⇨',
            'lastPageLabel'=>'⇛',
            'maxButtonCount'=>13,
        ],
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],
            'description',
            'date_start',
            'date_end',
            //'type',
            [
                'attribute'=>'pos_article',
                'label'=>'Топливо',
                'value' =>  function($model){
                    $fuels = \frontend\models\Fuel::getList();
                    //$type = $model->idShop->name;
                    return $fuels[$model->pos_article];
                } ,
                'filter' => \frontend\models\Fuel::getList(),
            ],
            [   'attribute'=>'shop_id',
                'label'=>'АЗС',
                'filter' => \frontend\models\Shops::getList(),
                'value'=>
                    function($model){
                        $type = $model->idShop->name;
                        return $type;
                    } ,
                /*['width'=>'100px']*/
            ],
            ['class' => 'yii\grid\ActionColumn',
                'buttons' => [
                    'copy' => function ($url, $model) {
                        $customurl = Yii::$app->getUrlManager()->createUrl(['action/copy', 'id' => $model['id']]);//$model->id для AR
                        return \yii\helpers\Html::a(
                            '<span class="glyphicon glyphicon-copy"></span>',
                            $customurl,
                            ['title' => Yii::t('yii', 'Копировать'), 'data-pjax' => '1']);
                    },
                ],
                'options' => [
                    'data-pjax' => true,
                ],
                'template' => '{view}&nbsp;|&nbsp;{copy}&nbsp;|&nbsp;{update}&nbsp;|&nbsp;{delete}',
            ],
        ],
    ]); ?>
    <?php Pjax::end(); ?></div>

frontend/views/action/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Action */

$this->title = Yii::t('app', 'Обновить {modelClass}: ', [
    'modelClass' => 'Action',
]) . $model->id;
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Акции'), 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = Yii::t('app', 'Обновить');
?>
<div class="action-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

frontend/views/action/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\Action */

$this->title = $model->id;
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Акции'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="action-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a(Yii::t('app', 'Изменить'), ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a(Yii::t('app', 'Удалить'), ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => Yii::t('app', 'Вы действительно хотите удалить акцию?'),
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [

            [
                'label' => 'Описание акции',
                'value' => $model->description,
            ],
            [
                'label' => 'Дата начала акции',
                'value' => $model->date_start,
            ],
            [
                'label' => 'Дата начала акции',
                'value' => $model->date_end,
            ],

            'type',
            'pos_article:ntext',
           'share_properties',
           /* 'share_properties_00',
            'share_properties_10',
            'share_properties_20',
            'share_properties_30',
            'share_properties_40',
            'share_properties_41',*/
            'shop_id',
        ],
    ]) ?>

</div>